spring.application.name=creator-board

spring.datasource.url=jdbc:mysql://localhost:3306/creatorboard
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# プロファイル切り替え（home/school環境）
spring.profiles.active=${SPRING_PROFILE:school}

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true